# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - graph-calendar-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_51ae82d723be4ef691e8e75bbce6b41d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f5dffaddbcae4604bca1fd046319f352 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_51ae82d723be4ef691e8e75bbce6b41d }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'graph-calendar-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7b54ffb57a6a48d58109f0103a63d9a1 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_51ae82d723be4ef691e8e75bbce6b41d }}/appsvc/staticsite:${{ github.sha }}'